name: CI

on:
  push:
    branches:
      - develop
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Create resource directories
      run: |
        mkdir -p src/main/resources
        mkdir -p src/test/resources
    
    - name: Set up secret yml file
      env:
        YAML_SECRET: ${{ secrets.YAML_SECRET }}
        YAML_DIR: src/main/resources
        YAML_TEST_DIR: src/test/resources
        YAML_FILE_NAME: application.yml
      run: |
        echo $YAML_SECRET | base64 --decode > $YAML_DIR/$YAML_FILE_NAME
        echo $YAML_SECRET | base64 --decode > $YAML_TEST_DIR/$YAML_FILE_NAME
        echo "YAML_SECRET has been decoded and saved to $YAML_DIR/$YAML_FILE_NAME"
        echo "YAML_SECRET has been decoded and saved to $YAML_TEST_DIR/$YAML_FILE_NAME"

    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: 6
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: test
      run: ./gradlew test
